### ISSUE TITLE
Crashes on load due to invalid buffer formats

### ISSUE THREAD

**Issue by ssylvan** [JJoosten/IndirectOcclusionCulling#1]
App crashes due to device being removed after loading the models

If I enable the debug layer I get this output after the model has been loaded:

D3D12 ERROR: ID3D12Device::CreateShaderResourceView: For the resource format D24_UNORM_S8_UINT, when making a D3D view, the format name for the view can't be R24_UNORM_X8_TYPELESS.  See documentation for the set of valid view format names for this resource format, determining which how the resource (or part of it) will appear to shader. [ STATE_CREATION ERROR #28: CREATESHADERRESOURCEVIEW_INVALIDFORMAT]
D3D12: Removing Device.

This fires on line 460 of scene.cpp.

I'm not quite sure why this fails, but I don't know D3D12 well enough. I would have thought those two formats should be compatible :-/

**Comment by ssylvan** [comment]
FYI, I was able to get past this by changing the format when creating the resource to "R24G8Typeless" (but leave everyting else the same). Unfortunately the sample still doesn't work - it just gives me a yellow screen, but the obvious crashing is at least gone.

**Comment by JJoosten** [comment]
Hy ssylvan, I found the issue with the yellow color. Thanks for the heads-up.

I didn't correctly patch up the material file for Sponza. It should be fixed now!  
I will look into the type format later tonight or tomorrow.

Cheers,

**Comment by ssylvan** [comment]
Can confirmt that this works - latest assets and my change to use a typeless format for the resource.

**Comment by JJoosten** [comment]
Hi ssylvan, I just tested your proposed fix by using R24G8Typeless and this actually breaks the program, since the depth buffer is not correctly represented. What GPU are you currently running on?
I tested on an Intel 5100, Nvidia GTX 750 TI and Nvidia GTX950.

**Comment by ssylvan** [comment]
I'm on a GTX 1080. 

To be clear: only the resource should be typeless, all the views need to have a fully specified type. I literally only changed the CreateCommittedResource call on 1147 in gfx_d3d12.cpp to pass in cfc::gpu_format_type::R24G8Typeless into the gpu_resource_desc::Tex2D constructor - everything else was left alone (obviously this is an ugly hack and shoudl be done in some cleaner way).

**Comment by ssylvan** [comment]
Oh, and I'm not a D3D12 expert, but I asked around on a slack channel with people who are and they told me that you're not supposed to use specified types for resoruces if you're going to alias them with multiple different types later (e.g. both DSV and SRVs with D24\* and R24\* types respectively). That seems to be true on my machine, so I'm not sure why yours works differently :-/

**Comment by Lijmer** [comment]
The typeless format is also required for aliasing in D3D11.

**Comment by JJoosten** [comment]
Hey ssylvan and Lijmer, sorry for the super super late reply. I have had a really busy time for the last months. Got around to fixing the issue tonight; it was minor. Also took the time to remove the setpowerstate functions since they are not working the same anymore after win10 millenium update.
